### ISSUE TITLE
No wireless interface on s905d devices

### ISSUE THREAD

**Issue by kuoruan** [150balbes/Build-Armbian#10]
My build command, with default kernel config.
```
./compile.sh BOARD=aml-g12 BRANCH=default RELEASE=disco BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no
```

```
Model: Phicomm N1
CPU: Amlogic S905D
RAM: 2G DDR3
8G eMMC
Ethernet: RTL8211F Gigabit Ethernet

WIFI/Bluetooth: CYW43455 ( same as Raspberry Pi 3B+ ) 5G WiFi IEEE 802.11n/ac with Integrated Bluetooth 4.1
```

Also tried this build: https://yadi.sk/d/srrtn6kpnsKz2/Linux/ARMBIAN/5.96_20190918

**Comment by kuoruan** [comment]
Anything else should I do? Modify the kernel config?

**Comment by 150balbes** [comment]
I do not support WiFi.

**Comment by kuoruan** [comment]
How can I add wifi myself?

With 5.91, the wifi works well.

**Comment by 150balbes** [comment]
Compare sources and look for errors.

**Comment by kuoruan** [comment]
Finally found the solution.
Your new kernel config not include the ```Broadcom FullMAC WLAN driver```
I enable it, rebuild and got the wlan back.

**Comment by kemadz** [comment]
FYI: a67db29e476003cd576880166d31305191fb5899 has enabled `CONFIG_BRCMFMAC`.
