### ISSUE TITLE
Build failling after stage 2

### ISSUE THREAD

**Issue by z17207** [150balbes/Build-Armbian#12]
This is similar to #11 

I am trying to build buster for S805 (`Full OS image for flashing -> Do not change the kernel configuration -> aml-s805 -> default -> buster -> Image with console interface (server) -> Standard image with console interface`) but I get this error every time:
```[ o.k. ] Installing base system [ Stage 2/2 ]
chroot: failed to run command ‘/bin/bash’: Exec format error
[ error ] ERROR in function create_rootfs_cache [ debootstrap.sh:160 ]
[ error ] Debootstrap base system second stage failed 
[ o.k. ] Process terminated 
[ o.k. ] Unmounting [ /home/builder/Build-Armbian/.tmp/rootfs-default-aml-s805-buster-no-no/ ]
[ error ] ERROR in function unmount_on_exit [ image-helpers.sh:66 ]
[ error ] debootstrap-ng was interrupted 
[ o.k. ] Process terminated
```

I'm trying to build it inside systemd-nspawn container(`systemd-nspawn -b`) @ ubuntu bionic guest (`debootstrap --include=systemd-container --components=main,universe bionic ubuntu-tree http://by.archive.ubuntu.com`) on Fedora 31 host.

Full log here: [paste.ubuntu.com](https://paste.ubuntu.com/p/CTZkDTqdRt/)

Any help please? Also I was trying to build another ROM for g12 and this fails with same error. I guess I miss something inside ubuntu system.

**Comment by 150balbes** [comment]
I can't help you, I only do all builds in VirtualBox with Ubuntu 19.

**Comment by z17207** [comment]
Successfully built using Virtualbox with ubuntu bionic
