### ISSUE TITLE
20200206 version  llegacy img has no dtb files

### ISSUE THREAD

**Issue by abcdelf** [150balbes/Build-Armbian#14]
hi, I get some problem.

I build the  s9xx **legacy version** ubuntu and debian img from this repo ，all of these img has no dtb files。i copy the dtb form the **current** version img , but the board can not boot into  the system .

The current version img is can work normal. but htop can not show the message corret!

My board is vim3, thanks.

**Comment by 150balbes** [comment]
> I build the s9xx **legacy version**

What kernel sources are used ?

**Comment by abcdelf** [comment]
kernel is 5.3， i just build your repo.  I don't add anything.

**Comment by 150balbes** [comment]
How did you determine that there is no DTB ?

**Comment by abcdelf** [comment]
yes , I build the legency version . I make the image to SD card , the SD has no DTB file.
as same , The current version , the SD has DTB file . and I copy the current DTB to the legency img ,but it not work

**Comment by 150balbes** [comment]
model (board) ?
