### ISSUE TITLE
Difference between this one and the origin one

### ISSUE THREAD

**Issue by ok000305** [150balbes/Build-Armbian#15]
What's the difference between this tv project and the origin armbian project?

**Comment by 150balbes** [comment]
Ask this question to users in this topic, I think they will be better able to explain these differences.
https://forum.armbian.com/topic/12162-single-armbian-image-for-rk-aml-aw/

**Comment by ok000305** [comment]
when compiling allwinner h6 for tv box, It went wrong like this:
  DTC     arch/arm/dts/sun50i-h6-eachlink-h6-mini.dtb
  DTC     arch/arm/dts/sun50i-h6-orangepi-3.dtb
  DTC     arch/arm/dts/sun50i-h6-beelink-gs1.dtb
start=$(ccache aarch64-linux-gnu-nm u-boot | grep __rel_dyn_start | cut -f 1 -d ' '); end=$(ccache aarch64-linux-gnu-nm u-boot | grep __rel_dyn_end | cut -f 1 -d ' '); tools/relocate-rela u-boot-nodtb.bin 0x4a000000 $start $end
  DTC     arch/arm/dts/sun50i-h6-orangepi-lite2.dtb
  DTC     arch/arm/dts/sun50i-h6-orangepi-one-plus.dtb
scripts/Makefile.lib:308: recipe for target 'arch/arm/dts/sun50i-h6-eachlink-h6-mini.dtb' failed
dts/Makefile:38: recipe for target 'arch-dtbs' failed
Makefile:1087: recipe for target 'dts/dt.dtb' failed
[ error ] ERROR in function compile_uboot [ compilation.sh:206 ]
[ error ] U-boot compilation failed 
[ o.k. ] Process terminated

**Comment by 150balbes** [comment]
Write down in full all the steps you do ( the exact commands you execute).

**Comment by ok000305** [comment]
step1:full os for image
step2:show kernel config before compillation
step3:choose aw-h6-tv
step4:choose current -> bionic
step5:server image -> standard

then I got the error code

**Comment by 150balbes** [comment]
fix
