### ISSUE TITLE
Isn't aml_s9xxx supported anymore?

### ISSUE THREAD

**Issue by sanbrother** [150balbes/Build-Armbian#16]
I downloaded the latest code (v20200408), and found that there is no options for aml_s9xxx.
Isn't aml_s9xxx supported anymore? Or is it merged into another configuration option?

Thanks for your great work!

**Comment by evaniswong** [comment]
You can use arm64 as all platform shares the same code afterward.

**Comment by sanbrother** [comment]
Great!
Thank you very very much.
