### ISSUE TITLE
How to make an image without building from source?

### ISSUE THREAD

**Issue by probonopd** [150balbes/Build-Armbian#17]
Hello @150balbes how do I make an image without building from source? I would like to make a Lubuntu image, for example.

**Comment by 150balbes** [comment]
You may need to refer to the Lubuntu build instructions.

**Comment by probonopd** [comment]
Hi @150balbes thanks for this very useful project and for your answer. I searched this project but could not find the Lubuntu build instructions, can you please share a link?

Also, I would like to use only already-compiled deb files, not compile the deb files myself.

**Comment by 150balbes** [comment]
I have no idea about the Lubuntu build system.

**Comment by sanbrother** [comment]
I didn't build any other system myself, well I guess, Lubuntu is ubuntu alike, you can fork this repo, do some modification to the build script (perhaps just replace the rootfs?)

By the way, why Lubuntu? Debian and ubuntu are pretty good.

**Comment by probonopd** [comment]
Or take Xubuntu or Ubuntu-MATE. I am interested in the usual desktops, not just the pre-produced Armbian images.

**Comment by probonopd** [comment]
We still do not understand how to make an image without building from source, for example a Lubuntu/Xubuntu/Kubuntu/... image.
