### ISSUE TITLE
s905d-phicomm-n1，Cannot enter the system again after writing emmc using the latest image

### ISSUE THREAD

**Issue by molun** [150balbes/Build-Armbian#18]
Use your mirror Armbian_20.05.2_Arm-64_buster_current_5.7.0-rc1_20200416.img.xz to write to PHICOMM N1 emmc, you can not enter the system, the screen does not display logo, pink, re-insert mirror U disk screen will flash, there is still no logo Won't enter the system
meson-gxl-s905d-phicomm-n1.dtb

**Comment by sanbrother** [comment]
@molun Where did you download it from? I wanna have a try.

**Comment by molun** [comment]
> @molun Where did you download it from? I wanna have a try.

https://yadi.sk/d/_rQgn_FosYuW0g
Maybe it is the problem of writing the script!
Unable to write for the first time, after using ./install-aml-s905-emmc.sh, it cannot enter the system normally, and the U disk cannot boot

**Comment by 150balbes** [comment]
s905d !=  s905  (not use install-aml-s905-emmc.sh)
