### ISSUE TITLE
Unable to drive EMMC

### ISSUE THREAD

**Issue by huijinkeji** [150balbes/Build-Armbian#21]
First of all thank you 150balbes. my device uses the scheme S805 and 8GB EMMC. i tried to compile S812 firmware using meson8b-odroidc1.dtb, can network but not recognize eMMC. using your compiled Armbian_5.67_Aml-s805_Ubuntu_bionic_default_3.10.108_desktop_20181207.img.xz can recognize. Can you help me?

**Comment by 150balbes** [comment]
These are completely different cores and drivers are not compatible with each other.

**Comment by huijinkeji** [comment]
Hi @150balbes ,thanks for answering my question, the meson8b-odroidc1.dtb I use is generated through this repository S812, not the extracted previous img. how should I modify it to support eMMC?

**Comment by 150balbes** [comment]
1. What is your exact model of TV box ? 
2. Write in detail what steps you are taking and what you want to get.
