### ISSUE TITLE
ERROR in function compile_uboot

### ISSUE THREAD

**Issue by Gausus** [150balbes/Build-Armbian#26]
scripts/kconfig/conf  --syncconfig Kconfig
  CFG     u-boot.cfg
  GEN     include/autoconf.mk.dep
  CFG     spl/u-boot.cfg
  CFG     tpl/u-boot.cfg
scripts/Makefile.autoconf:77: recipe for target 'u-boot.cfg' failed
scripts/Makefile.autoconf:48: recipe for target 'include/autoconf.mk.dep' failed
scripts/Makefile.autoconf:80: recipe for target 'spl/u-boot.cfg' failed
scripts/Makefile.autoconf:84: recipe for target 'tpl/u-boot.cfg' failed
[ error ] ERROR in function compile_uboot [ compilation.sh:235 ]
[ error ] U-boot compilation failed 
[ o.k. ] Process terminated

**Comment by 150balbes** [comment]
There is no detailed description of the steps, the question is closed.
