### ISSUE TITLE
toolchain download in only_mode failed for me

### ISSUE THREAD

**Issue by burnbabyburn** [150balbes/Build-Armbian#27]
Using osboxes ubuntu 20.4 amd64 VM

Problem: Downloading the toolchain via compile.sh doesnt work for me(errorCode=3 Ressource not found on dotsrc,imola.armbian,mirrors.tuna)

What works:

- Getting the toolchain via "original" armbian script and copying it over
- apt
- firefox

Possible cause: The origin project added more mirrors to the webseed and some mirrors are unreachable:

> WEBSEED=(
> 	"https://dl.armbian.com/"
> 	"https://imola.armbian.com/dl/"
> 	"https://mirrors.netix.net/armbian/dl/"
> 	"https://mirrors.dotsrc.org/armbian-dl/"
> 	"https://us.mirrors.fossho.st/armbian/dl/"
> 	"https://uk.mirrors.fossho.st/armbian/dl/"
> 	"https://armbian.systemonachip.net/dl/"
> 	) 
from lib/general.sh

maybe its just a temporary error with the website or a problem on my side. Feel free to close without comment

**Comment by 150balbes** [comment]
Read the instructions carefully, you are not using the build system correctly.
