### ISSUE TITLE
Error kernel was not built [@host]

### ISSUE THREAD

**Issue by ericmigi** [150balbes/Build-Armbian#28]
Just tried compiling again today, received this error  when running `./compile.sh docker BOARD="arm-64" RELEASE="buster" KERNEL_ONLY="no" BUILD_DESKTOP="no" BUILD_MINIMAL="no" KERNEL_CONFIGURE="no"`

```
[ error ] ERROR in function compile_kernel [ compilation.sh:434 ]
[ error ] Kernel was not built [ @host ]
[ o.k. ] Process terminated 
```

**Comment by ericmigi** [comment]
also it looks like the git history for this repo has changed? Where did your commit from January go?

**Comment by Hondough** [comment]
Hi Eric, Oleg posted on the forum this will be locked to certain AML devices. That wouldn't work if there is a clear history of commits as people would just omit the commits that implement this. If you want history you'll need to use somebody else's fork.

https://forum.armbian.com/topic/15490-information-for-users-of-tv-boxes-on-the-amlogic-platform/

>>For some AML devices (for which there will be support), their own images will be released, specifically designed for this equipment, with protection from use by thieves and pirates. These images will be protected from use on devices that are not intended for this purpose. When trying to run on non-intended devices, users will have problems (immediately or over time, clearly visible or hidden, such as the gradual destruction of the system, etc.).
