### ISSUE TITLE
[ error ] ERROR in function compile_uboot [ compilation.sh:235 ]

### ISSUE THREAD

**Issue by boza111** [150balbes/Build-Armbian#29]
When trying to build with ./compile.sh I get the following error.
The files are not modified and I am using the default settings.

`[ o.k. ] * [l][c] add-emmc-support-for-nanopi-k2.patch
[ o.k. ] * [l][c] enable-DT-overlays-support.patch
[ o.k. ] * [l][c] le-potato-general-vendor.patch
[ o.k. ] * [l][c] u-boot-meson64-support-old-bootscripts.patch
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
scripts/kconfig/conf  --syncconfig Kconfig
#
# configuration written to .config
# 
  CHK     include/config.h
  UPD     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk.dep
[ error ] ERROR in function compile_uboot [ compilation.sh:235 ]
[ error ] U-boot compilation failed
[ o.k. ] Process terminated`

**Comment by 150balbes** [comment]
You didn't specify any details about what you're trying to collect.

**Comment by boza111** [comment]
I am trying to compile on arm computer (not x86).
This error happens for every board.

Do you have any idea?

**Comment by 150balbes** [comment]
> on arm computer (not x86)

> for every board

Should  invite a psychic to guess on which device, using which image, with which parameters the build is performed, etc.?

**Comment by boza111** [comment]
I have tried many different boards for example the odroid n2. I didn't use build parameters and just pressed the enter key for the default options. The result was this error for every single board (and build parameter).

After looking at the code I see that the build tool cannot compile on the ARM cpu because of  "make CROSS_COMPILE=" . This results in the build tool choosing an x86 compiler.

I have found the issue now. You can close this issue.
