### ISSUE TITLE
Hardware of choice

### ISSUE THREAD

**Issue by LeosSire** [150balbes/Build-Armbian#3]
Good afternoon,

I have been trying to install other instances of your projects on a Nexbox A95x (S905x) system but it hangs on "__primary_switched+0x5c/0x64", I've seen patches in the past to correct this on the "numa.c" as seen here: https://patchwork.kernel.org/patch/9385891/

Needless to say, it didn't work. Frustrating. 

I'm been trying to get this to work for a while and not been successful. I have found precompiled images but the wifi doesn't work (kernel 4.1 issue). These are from your Yandisk drive. 

Please can you advise what hardware you have tested this on? 

I'm compiling this newest branch/project right now to try.

Is the output format suitable for the Amlogic's USB upgrade tool? Or does it result in the broken down images and FS?

I know this isn't an issue, but there isn't a forum per project. 

Thank you,

**Comment by 150balbes** [comment]
> I have been trying to install other instances of your projects on a Nexbox A95x (S905x) system but it hangs on "__primary_switched+0x5c/0x64",

Show all startup log from UART console.

> Please can you advise what hardware you have tested this on?

I'm testing on Khadas VIM1 S905X. WiFi works on this model.



> Is the output format suitable for the Amlogic's USB upgrade tool? Or does it result in the broken down images and FS?

These images are intended only for writing to SD or USB media. They cannot be used for USB Built Tools.


> I know this isn't an issue, but there isn't a forum per project.

https://forum.armbian.com/topic/7802-new-git-for-version-assembly-armbian-for-tv-boxes/
