### ISSUE TITLE
usb boot issue caused by boot_targets in u-boot.ext

### ISSUE THREAD

**Issue by cattyhouse** [150balbes/Build-Armbian#30]
At least in `u-boot-s905 and u-boot-s905x-s912` the `boot_targets=romusb mmc0 mmc1 mmc2 usb0 pxe dhcp` could cause a small issue

if this version of u-boot is installed in both mmc and usb, then usb boot will be ignored, it always boot into mmc no matter usb is connected or not. suggestions:

`boot_targets=romusb mmc0 mmc1 mmc2 usb0 pxe dhcp` - before
`boot_targets=usb0 romusb mmc0 mmc1 mmc2 pxe dhcp` - after

which makes usb0 the highest priority

i already used a hex editor to modify this string, and it is confirmed to work. when usb is connected, it will boot from usb, when no usb connected, it will boot from mmc. 

hope this is the correct place to submit the issue.

**Comment by 150balbes** [comment]
If I understood your question correctly, this is a long time ago implemented. 

https://github.com/150balbes/Build-Armbian/blob/master/patch/u-boot/u-boot-arm-64/u-boot-meson64-usb.patch


P.S. AML is now a low priority for me.

**Comment by cattyhouse** [comment]
wow, there is a patch? good to know, but the u-boot.xxx binary provided in [link](https://disk.yandex.ru/d/_rQgn_FosYuW0g/20.10/20201014) seems not get the patch applied

**Comment by cattyhouse** [comment]
Anyway, thanks for your great u-boot binary, i'm finally able to chainload it and boot 5.10.x (which removed text_offset bit), close for solved.
