### ISSUE TITLE
Difference to https://github.com/150balbes/build?

### ISSUE THREAD

**Issue by probonopd** [150balbes/Build-Armbian#4]
Hello, thanks for your great work on Amlogic systems. What is the difference to https://github.com/150balbes/build?

**Comment by 150balbes** [comment]
https://forum.armbian.com/topic/7802-new-git-for-version-assembly-armbian-for-tv-boxes/

**Comment by probonopd** [comment]
Thank you very much for these very useful projects. I am trying to build for a s805 target (MXQ box).

https://forum.armbian.com/topic/7802-new-git-for-version-assembly-armbian-for-tv-boxes/ says this is the new GitHub project. Will it support building for s805 targets too? Probably e.g., these files need to be copied into this project?

```
https://github.com/150balbes/build/blob/amlogic/config/boards/vegas805.conf
https://github.com/150balbes/build/blob/amlogic/config/sources/vegas805.conf
https://github.com/150balbes/build/blob/amlogic/config/kernel/linux-vegas805-default.config
https://github.com/150balbes/build/blob/amlogic/config/bootscripts/boot-vegas805.cmd
```
