### ISSUE TITLE
Can't use realtek UART bluetooth

### ISSUE THREAD

**Issue by ChalesYu** [150balbes/Build-Armbian#5]
when I'm running `./8822b_hciattach -n -s 115200 /dev/ttyAML1  rtk_h5`
it show me some error:
```
Can't set device: Protocol not supported
Can't initialize device: Protocol not supported
```
full error log is here :  [errorlog.txt](https://github.com/150balbes/Build-Armbian/files/2476332/errorlog.txt)

Please set  `CONFIG_BT_HCIUART_3WIRE=y`  to kernel config
Thanks

**Comment by probonopd** [comment]
Which exact device/PCB are you using?

**Comment by ChalesYu** [comment]
Device is MGV2000
I can use meson-gxl-s805x-p241.dts to boot it.

**Comment by 150balbes** [comment]
> Please set `CONFIG_BT_HCIUART_3WIRE=y` to kernel config

I will check if this does not interfere with other devices, I will add to the default config.

**Comment by ChalesYu** [comment]
Although this issue can be solved by completely recompile kernel, I will try to recompile part of the kernel module.

anyway, seems this issue has been sloved. I will close this issue
