### ISSUE TITLE
How to build for S805?

### ISSUE THREAD

**Issue by probonopd** [150balbes/Build-Armbian#7]
Need to build an image for the MXQ box (PCB: S805Q_V2.0) 

It identifies itself as `m8b_m201_v1@23a35625` and can be booted with `meson8b_m201d.dtb`.

https://forum.armbian.com/topic/7802-new-git-for-version-assembly-armbian-for-tv-boxes/ says this is the new GitHub project. Will it support building for s805 targets too? Probably e.g., these files need to be copied into this project?

```
https://github.com/150balbes/build/blob/amlogic/config/boards/vegas805.conf
https://github.com/150balbes/build/blob/amlogic/config/sources/vegas805.conf
https://github.com/150balbes/build/blob/amlogic/config/kernel/linux-vegas805-default.config
https://github.com/150balbes/build/blob/amlogic/config/bootscripts/boot-vegas805.cmd
```

**Comment by probonopd** [comment]
Hello @150balbes, this was closed - but what is the answer?
Thanks.

**Comment by 150balbes** [comment]
Support for the S805 has already been added to the build system.
https://github.com/150balbes/Build-Armbian/tree/master/config/boards

**Comment by probonopd** [comment]
Thank you
